-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "chat_guid" TEXT not null,
  "message_guid" TEXT not null,
  "prompt" TEXT not null,
  "cwd" TEXT,
  "status" TEXT CHECK ("status" IN ('queued', 'running', 'done', 'failed', 'stopped')) default 'queued',
  "reply" TEXT,
  "error" TEXT,
  "session_id" TEXT,
  "cost_usd" REAL,
  "duration_ms" INTEGER,
  "last_activity" TEXT,
  "started_at" INTEGER,
  "finished_at" INTEGER,
  "conversation_id" INTEGER REFERENCES "conversations"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
INSERT INTO "_qb_tmp_runs" ("id", "chat_guid", "message_guid", "prompt", "cwd", "status", "reply", "error", "session_id", "cost_usd", "duration_ms", "last_activity", "started_at", "finished_at", "conversation_id", "created_at", "updated_at") SELECT "id", "chat_guid", "message_guid", "prompt", "cwd", "status", "reply", "error", "session_id", "cost_usd", "duration_ms", "last_activity", "started_at", "finished_at", "conversation_id", "created_at", "updated_at" FROM "runs";
DROP TABLE "runs";
ALTER TABLE "_qb_tmp_runs" RENAME TO "runs";
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
