-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "licenses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key" TEXT not null,
  "email" TEXT,
  "plan" TEXT CHECK ("plan" IN ('monthly', 'yearly', 'lifetime')) not null,
  "status" TEXT not null,
  "stripe_customer_id" TEXT,
  "stripe_subscription_id" TEXT,
  "stripe_checkout_session_id" TEXT not null,
  "current_period_end" INTEGER,
  "checked_at" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "licenses_key_unique" ON "licenses" ("key");
CREATE UNIQUE INDEX IF NOT EXISTS "licenses_stripe_checkout_session_id_unique" ON "licenses" ("stripe_checkout_session_id");
