-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "conversations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "chat_guid" TEXT not null,
  "handle" TEXT not null,
  "service" TEXT default 'iMessage',
  "session_id" TEXT,
  "cwd" TEXT,
  "last_active_at" INTEGER,
  "more_text" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "conversations_chat_guid_unique" ON "conversations" ("chat_guid");
