-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "chat_guid" TEXT not null,
  "message_guid" TEXT not null,
  "prompt" TEXT not null,
  "cwd" TEXT,
  "status" TEXT CHECK ("status" IN ('queued', 'running', 'done', 'failed', 'stopped')) default 'queued',
  "reply" TEXT,
  "error" TEXT,
  "session_id" TEXT,
  "cost_usd" INTEGER,
  "duration_ms" INTEGER,
  "last_activity" TEXT,
  "started_at" INTEGER,
  "finished_at" INTEGER,
  "conversation_id" INTEGER REFERENCES "conversations"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
